apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: ainureg/prod_made
      name: fastapi-ml
      ports:
        - containerPort: 8000
