version: 1
formatters:
  simple:
    class: logging.Formatter
    format: "%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  full:
    class: logging.Formatter
    format: "%(levelname)s %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"    
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  error_handler:
    class: logging.FileHandler
    level: WARN
    filename: errors.logs
    formatter: full
loggers:
  homework1:
    level: DEBUG
    handlers: [console]
    propogate: no
  faker.factory:
    level: CRITICAL
root:
  level:
  handlers:
